services:
  - type: web
    name: song-generator-11
    env: docker
    plan: free
    region: frankfurt
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://song-generator-11.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d4rd5gogjchc73bqkpb0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: song_generator_db
      - key: DB_USERNAME
        value: song_generator_db_user
      - key: DB_PASSWORD
        value: Ytj6pS3Y6OwtkBU5bm4XCvY6L1Xm5P1b
